#!/bin/bash

# Setup script to generate Firebase config files from environment variables
# Usage: source .env && ./postman/setup-firebase-config.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "🔧 Setting up Firebase configuration from environment variables..."
echo ""

# Check if .env file exists
if [ -f "$PROJECT_ROOT/.env" ]; then
    echo "📄 Loading .env file..."
    set -a
    source "$PROJECT_ROOT/.env"
    set +a
fi

# Get Firebase API key from environment or prompt
if [ -z "$FIREBASE_API_KEY" ]; then
    echo "⚠️  FIREBASE_API_KEY not found in environment"
    read -p "Enter your Firebase API key: " FIREBASE_API_KEY
    if [ -z "$FIREBASE_API_KEY" ]; then
        echo "❌ API key is required"
        exit 1
    fi
fi

# Set defaults
FIREBASE_AUTH_DOMAIN="${FIREBASE_AUTH_DOMAIN:-cloud-secrets-manager.firebaseapp.com}"
FIREBASE_PROJECT_ID="${FIREBASE_PROJECT_ID:-cloud-secrets-manager}"

echo "✅ Using configuration:"
echo "   API Key: ${FIREBASE_API_KEY:0:20}..."
echo "   Auth Domain: $FIREBASE_AUTH_DOMAIN"
echo "   Project ID: $FIREBASE_PROJECT_ID"
echo ""

# Generate firebase-config.js
echo "📝 Generating firebase-config.js..."
cat > "$SCRIPT_DIR/firebase-config.js" << EOF
// Firebase configuration loaded from environment variables
// This file is auto-generated by setup-firebase-config.sh
// DO NOT commit this file - it's in .gitignore

const firebaseConfig = {
    apiKey: "${FIREBASE_API_KEY}",
    authDomain: "${FIREBASE_AUTH_DOMAIN}",
    projectId: "${FIREBASE_PROJECT_ID}"
};

// Make it available globally
if (typeof window !== 'undefined') {
    window.firebaseConfig = firebaseConfig;
}

if (typeof module !== 'undefined' && module.exports) {
    module.exports = firebaseConfig;
}
EOF

# Update get-token.js to use the config
echo "📝 Updating get-token.js..."
cat > "$SCRIPT_DIR/get-token.js" << 'ENDOFFILE'
// Quick script to get Google ID token
// Run in browser console on a page with Firebase SDK loaded
// 
// ⚠️ SECURITY: This file uses firebase-config.js which is generated from environment variables
// DO NOT commit firebase-config.js to Git!

// Load Firebase config from generated file
let firebaseConfig;
if (typeof require !== 'undefined') {
    // Node.js environment
    firebaseConfig = require('./firebase-config.js');
} else if (typeof window !== 'undefined' && window.firebaseConfig) {
    // Browser environment (config loaded via script tag)
    firebaseConfig = window.firebaseConfig;
} else {
    throw new Error("Firebase config not found. Run setup-firebase-config.sh first or load firebase-config.js in HTML");
}

// For browser console:
if (typeof firebase !== 'undefined') {
    const app = firebase.initializeApp(firebaseConfig);
    const auth = firebase.auth();
  
    // ⚠️ SECURITY: Replace with your actual email and password
    const email = process.env.FIREBASE_EMAIL || "YOUR_EMAIL_HERE"; // Replace with your email
    const password = process.env.FIREBASE_PASSWORD || "YOUR_PASSWORD_HERE"; // Replace with your password
  
    auth.signInWithEmailAndPassword(email, password)
        .then((userCredential) => {
            return userCredential.user.getIdToken();
        })
        .then((idToken) => {
            console.log("✅ ID Token:");
            console.log(idToken);
            console.log("\n📋 Copy this token and set it in Postman environment variable: google_id_token");
        })
        .catch((error) => {
            console.error("❌ Error:", error.message);
        });
} else {
    console.log("Firebase SDK not loaded. Use this in browser console with Firebase SDK.");
}
ENDOFFILE

# Update get-id-token.html to use the config
echo "📝 Updating get-id-token.html..."
# Read the HTML file and replace the config section
sed -i.bak '/const firebaseConfig = {/,/};/c\
        // Firebase configuration loaded from firebase-config.js (generated from env vars)\
        // Make sure firebase-config.js is loaded before this script\
        if (!window.firebaseConfig) {\
            console.error("❌ firebase-config.js not loaded. Run setup-firebase-config.sh first.");\
        }\
        const firebaseConfig = window.firebaseConfig || {\
            apiKey: "YOUR_FIREBASE_API_KEY_HERE",\
            authDomain: "cloud-secrets-manager.firebaseapp.com",\
            projectId: "cloud-secrets-manager"\
        };
' "$SCRIPT_DIR/get-id-token.html"

# Add script tag to load firebase-config.js before the main script
if ! grep -q "firebase-config.js" "$SCRIPT_DIR/get-id-token.html"; then
    # Insert before the Firebase SDK scripts
    sed -i.bak '/<!-- Firebase SDK -->/a\
    <!-- Firebase Config (generated from env vars) -->\
    <script src="firebase-config.js"></script>
' "$SCRIPT_DIR/get-id-token.html"
fi

# Clean up backup files
rm -f "$SCRIPT_DIR/get-id-token.html.bak"

echo ""
echo "✅ Setup complete!"
echo ""
echo "📋 Next steps:"
echo "   1. Create a .env file in project root with:"
echo "      FIREBASE_API_KEY=your_api_key_here"
echo "      FIREBASE_AUTH_DOMAIN=cloud-secrets-manager.firebaseapp.com"
echo "      FIREBASE_PROJECT_ID=cloud-secrets-manager"
echo ""
echo "   2. Run this script again: ./postman/setup-firebase-config.sh"
echo ""
echo "   3. Open get-id-token.html in your browser"
echo ""

