apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: secret-service-monitor
  namespace: cloud-secrets-manager
  labels:
    app: secret-service
    release: prometheus
spec:
  selector:
    matchLabels:
      app: secret-service
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
    scrapeTimeout: 10s
    scheme: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_service_name]
      targetLabel: service
    - targetLabel: job
      replacement: secret-service
  namespaceSelector:
    matchNames:
    - cloud-secrets-manager

