{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: secret-service-pdb
  labels:
    app.kubernetes.io/name: secret-service
    app.kubernetes.io/part-of: csm-platform
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: secret-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: audit-service-pdb
  labels:
    app.kubernetes.io/name: audit-service
    app.kubernetes.io/part-of: csm-platform
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: audit-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: notification-service-pdb
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: csm-platform
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: notification-service
{{- end }}
