{{- $accounts := dict
  "secret-service" .Values.secretService.serviceAccount.gcpEmail
  "audit-service" .Values.auditService.serviceAccount.gcpEmail
  "notification-service" .Values.notificationService.serviceAccount.gcpEmail
}}
{{- range $name, $email := $accounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
    {{- include "csm.labels" $ | nindent 4 }}
  {{- if $email }}
  annotations:
    iam.gke.io/gcp-service-account: {{ $email }}
  {{- end }}
{{- end }}
