apiVersion: v1
kind: Namespace
metadata:
  name: csm
  labels:
    app.kubernetes.io/part-of: cloud-secrets-manager
    environment: minikube
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: cloud-secrets-manager
    environment: minikube
